export const START_TASK_CALL = "START_TASK_CALL"
export const TASK_CALL_FAILED = "TASK_CALL_FAILED"

export const CREATE_TASK = 'CREATE_TASK'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'

export const GET_USER_TASKS = 'GET_USER_TASKS'
export const GET_USER_TASKS_SUCCESS = 'GET_USER_TASKS_SUCCESS'

export const GET_ASSIGNED_TASKS = 'GET_ASSIGNED_TASKS'
export const GET_ASSIGNED_TASKS_SUCCESS = 'GET_ASSIGNED_TASKS_SUCCESS'

export const GET_TASK = 'GET_TASK'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'

export const UPDATE_TASK = 'UPDATE_TASK'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'

export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'

export const TASK_DISMISS_ERROR = 'TASK_DISMISS_ERROR'